package council

// Strategy identifies the deliberation algorithm used by a CouncilType.
type Strategy int

const (
	// PeerReview runs the 3-stage Karpathy pipeline: parallel generation →
	// anonymous peer ranking → chairman synthesis. Implemented in runner.go.
	PeerReview Strategy = iota

	// RoleBased runs a 2-stage pipeline: parallel specialist roles → chairman
	// synthesis. Stage 2 (peer ranking) is skipped; a stub Stage2CompleteData
	// event is emitted for SSE compatibility. Implemented in rolebased.go.
	RoleBased

	// Majority runs independent generation followed by a vote (exact match,
	// cluster, or weighted). Selects rather than synthesises. Not implemented.
	Majority

	// GenerateRankRefine runs parallel generation, ranks candidates against
	// structured criteria, then refines the top-K. Not implemented.
	GenerateRankRefine

	// MultiAgentDebate runs initial answers followed by N rounds of mutual
	// critique and revision, then synthesises. Not implemented.
	MultiAgentDebate

	// MixtureOfAgents runs a layered architecture: proposers → aggregators →
	// refiner. Not implemented.
	MixtureOfAgents

	// Delphi runs multiple anonymous blind rating rounds with averaged ratings.
	// Not implemented.
	Delphi
)

// Role defines a named participant with a specific mandate in a role-based council.
type Role struct {
	Name        string `json:"name"`
	Instruction string `json:"instruction"` // system-level prompt for this role
}

// CouncilType describes a named council configuration.
// QuorumMin of 0 means use the formula: max(2, ⌈N/2⌉+1).
type CouncilType struct {
	Name          string
	Strategy      Strategy
	Models        []string // Council members. RoleBased assigns models to Roles by index mod len; other strategies use all.
	Roles         []Role   // RoleBased only: role definitions with specialist instructions.
	ChairmanModel string
	Temperature   float64
	QuorumMin     int // 0 = use formula: max(2, ⌈N/2⌉+1)
}

// ChatMessage is a single turn in a conversation history.
type ChatMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

// ResponseFormat instructs the LLM to return a specific format.
type ResponseFormat struct {
	Type string `json:"type"` // e.g. "json_object"
}

// CompletionRequest is sent to the LLM gateway.
type CompletionRequest struct {
	Model          string          `json:"model"`
	Messages       []ChatMessage   `json:"messages"`
	Temperature    float64         `json:"temperature"`
	ResponseFormat *ResponseFormat `json:"response_format,omitempty"`
}

// CompletionResponse is received from the LLM gateway.
type CompletionResponse struct {
	Choices []struct {
		Message ChatMessage `json:"message"`
	} `json:"choices"`
}

// EventFunc is the callback used to stream stage-completion events to the caller.
type EventFunc func(eventType string, data any)

// StageOneResult holds a single council member's generated answer.
type StageOneResult struct {
	Label      string `json:"label"`      // anonymised label, e.g. "Response A"
	Content    string `json:"content"`
	Model      string `json:"model"`
	DurationMs int64  `json:"duration_ms"` // elapsed milliseconds
	Error      error  `json:"-"`
}

// StageTwoResult holds a single council member's peer-review rankings.
type StageTwoResult struct {
	ReviewerLabel string   `json:"reviewer_label"`
	Rankings      []string `json:"rankings"` // ordered labels, best first
	Error         error    `json:"-"`
}

// StageThreeResult holds the chairman's synthesised final answer.
type StageThreeResult struct {
	Content    string `json:"content"`
	Model      string `json:"model"`
	DurationMs int64  `json:"duration_ms"` // elapsed milliseconds
	Error      error  `json:"-"`
}

// RankedModel pairs a model name with its aggregate rank score.
type RankedModel struct {
	Model string  `json:"model"`
	Score float64 `json:"score"`
}

// Metadata is persisted with every assistant message.
type Metadata struct {
	CouncilType       string        `json:"council_type"`
	LabelToModel      map[string]string `json:"label_to_model"`
	AggregateRankings []RankedModel `json:"aggregate_rankings"`
	ConsensusW        float64       `json:"consensus_w"`
}

// Stage2CompleteData is the payload emitted by Runner for the "stage2_complete" event.
// It bundles peer-review results with the computed aggregate metadata so callers
// (e.g. the SSE handler) can surface both in one event.
type Stage2CompleteData struct {
	Results  []StageTwoResult `json:"results"`
	Metadata Metadata         `json:"metadata"`
}

// AssistantMessage is the full deliberation record stored with each assistant turn.
type AssistantMessage struct {
	Role     string           `json:"role"`
	Stage1   []StageOneResult `json:"stage1"`
	Stage2   []StageTwoResult `json:"stage2"`
	Stage3   StageThreeResult `json:"stage3"`
	Metadata Metadata         `json:"metadata"`
}

// ClarificationQuestion is a single question generated by a council member or chairman.
type ClarificationQuestion struct {
	ID   string `json:"id"`
	Text string `json:"text"`
}

// ClarificationAnswer is the user's response to a single clarification question.
type ClarificationAnswer struct {
	ID   string `json:"id"`
	Text string `json:"text"`
}

// ClarificationRound holds one round of clarification Q&A.
// Answers is empty until the user submits a response.
type ClarificationRound struct {
	Round       int                     `json:"round"`
	Questions   []ClarificationQuestion `json:"questions"`
	Answers     []ClarificationAnswer   `json:"answers"`
	CouncilType string                  `json:"council_type,omitempty"` // persisted on round-1
}

// ClarificationConfig holds Stage 0 operational limits.
type ClarificationConfig struct {
	MaxRounds            int
	MaxTotalQuestions    int
	MaxQuestionsPerRound int
}
